[package]
name = "pizza-baby"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
postgres = "0.19.7"
serde = "1.0.136"

[[bin]]
name = "main"
path = "src/interfaces/restful.rs"
